name:          10up Engineering Best Practices
description:   Project engineering best practices used by 10up.
url:           http://10up.github.io/Engineering-Best-Practices/

markdown:      redcarpet
permalink:     pretty
highlighter:   pygments
encoding:      utf-8