name:          Kanopi Engineering Best Practices
title:         Kanopi Engineering Best Practices
description:   Engineering best practices used by Kanopi.
url:           https://kanopi.github.io/
baseurl:       /Engineering-Best-Practices
author:
  name:    Kanopi
  email:   sales@kanopi.com
  github:  kanopi
  twitter: kanopi

markdown:      kramdown
permalink:     pretty
highlighter:   rouge
encoding:      utf-8
kramdown:
  input: GFM
sass:
  sass_dir: _includes/_sass
