name:          10up Engineering Best Practices
title:         10up Engineering Best Practices
description:   Engineering best practices used by 10up.
url:           https://10up.github.io/
baseurl:       /Engineering-Best-Practices
author:
  name:    10up
  email:   sales@10up.com
  github:  10up
  twitter: 10up

markdown:      kramdown
permalink:     pretty
highlighter:   rouge
encoding:      utf-8
kramdown:
  input: GFM
sass:
  sass_dir: _includes/_sass
